services:
  - type: web
    name: vicky-chatbot-app
    env: python
    plan: free
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: gunicorn vicky_app:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: PORT
        value: 8000
      - key: GEMINI_API_KEY
        sync: false
      - key: DISCORD_WEBHOOK
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_USERNAME
        sync: false
      - key: ADMIN_KEY
        sync: false
    healthCheckPath: /api/info
