services:
  - type: web
    name: vicky-chatbot-app
    env: python
    plan: free
    region: oregon
    buildCommand: |
      python -m pip install --upgrade pip==23.3.1
      python -m pip install setuptools==68.2.2 wheel==0.42.0
      python -m pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT --workers 4
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: PORT
        value: 8000
      - key: DISABLE_COLLECTSTATIC
        value: 1
      - key: PYTHONUNBUFFERED
        value: 1
      - key: GEMINI_API_KEY
        sync: false
      - key: DISCORD_WEBHOOK
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_USERNAME
        sync: false
      - key: ADMIN_KEY
        sync: false
    healthCheckPath: /api/info
